# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-19 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20161019_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='puplish',
            new_name='publish',
        ),
    ]
